on:
  push:
    tags:
      - 'v*'

name: Github Actions Release
run-name: Automating release package

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          bodyFile: "changeLogs/release-${{ github.ref_name }}.md"