on:
  push:
    branch:
      - '*'

name: Github on branch push
run-name: Verify test after push

jobs:
  build:
    name: Check test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
      - run: python -c "import sys; print(sys.version)"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: py.test -v